---
title: "Model Building and Absolute Risk Estimation""
output: html_notebook
---

Females

```{r}
rm(list=ls())
#####R CMD INSTALL -l /users/skim1/ myRPackage.tar.gz for package installation
library(dplyr)
library(iCARE)
library(eeptools)
library(survminer)
library(survival)
myfem=readRDS("/users/skim1/052020/data/female.final.11182021")

eid=readRDS("/users/skim1/052020/data/eid.final.10022021")
trfem=myfem[which(myfem$eid %in% eid),]
tefem=myfem[-which(myfem$eid %in% eid),]

cox.female=coxph(Surv(age_at_study_entry,cancer_incidence_age,female_overall_cancer_incidence)~blad_std+brea_std+colo_std+endo_std+kidn_std+lung_std+mela_std+nhl_std+ovar_std+panc_std+bmi+fhx_yes_no_fem+smoking_status+I(PYOS/10)+pc1+pc2+pc3+pc4+pc5+pc6+pc7+pc8+pc9+pc10,data=trfem)
summary(cox.female)

##############################################################################
termL <- attr(terms(cox.female), "term.labels")
a=predict(cox.female,tefem, type="terms",terms=termL[c(1:14)])
head(a)
lpnew.train=rowSums(predict(cox.female,trfem, type="terms",terms=termL[c(1:14)]))
lpnew.test=rowSums(predict(cox.female,tefem, type="terms",terms=termL[c(1:14)]))
lpnew.train.std=lpnew.train/sd(lpnew.train)
lpnew.test.std=lpnew.test/sd(lpnew.test)
trfem$lp=lpnew.train.std
tefem$lp=lpnew.test.std
cox.female.test=coxph(Surv(age_at_study_entry,cancer_incidence_age,female_overall_cancer_incidence)~lp+pc1+pc2+pc3+pc4+pc5+pc6+pc7+pc8+pc9+pc10,data=tefem)
concordance(cox.female.test)
summary(cox.female.test)$coefficients
library(RISCA)
tefem=data.frame(tefem)
tefem$futime=tefem$cancer_incidence_age-tefem$age_at_study_entry
auc5=roc.time(times="futime", failures="female_overall_cancer_incidence", variable="lp",
                    confounders=~1, data=tefem, 
                    pro.time=5, precision=seq(0.01,0.99, by=0.01))
auc5$auc

##############################################################################
#iCARE 
beta=as.matrix(cox.female.test$coefficients[1])
row.names(beta)="cPRS"
trfem$cPRS=trfem$lp
row.names(beta)="cPRS"
trfem$cPRS=trfem$lp
test=as.vector(tefem$lp)
test=test[order(test)]
test=data.frame(test)
colnames(test)="cPRS"
cal=11
ref=data.frame(rnorm(10000,mean=mean(trfem$lp),sd=sd(trfem$lp)))
colnames(ref)="cPRS"
v1 = list(); v1$name = "cPRS"; v1$type = "continuous"
cov_info_0=list(v1)
model_form_0=female_overall_cancer_incidence ~ cPRS
##############################################################################
incidence_rate=read.csv("/users/skim1/052020/FINAL_SNP_PROJECT/incidence_rate_seer_stat_08122020_female.csv")
inc=incidence_rate[,c(2,16)]
inc[,2]=inc[,2]/100000
##############################################################################
##1YEAR
##############################################################################
age_from=c(50:85)
age_to=age_from+1
age_int=rep(1,length(age_from))
ppv_1yr=matrix(data=NA,nrow=length(age_from), ncol=53532,byrow = FALSE,dimnames = NULL)
ppv_1yr[,1]=rep("female",nrow(ppv_1yr))
ppv_1yr[,2]=rep(paste0(age_from,"-",age_to),1)
##############################################################################
for (i in 1:length(age_from)){
  res_covs_snps=computeAbsoluteRisk(model.formula= model_form_0, 
                                    model.cov.info=cov_info_0, 
                                    model.log.RR=beta,
                                    model.ref.dataset = ref,
                                    model.disease.incidence.rates=inc,
                                    apply.age.start=age_from[i],
                                    apply.age.interval.length = 1,
                                    apply.cov.profile=test)
  ppv_1yr[i,c(3:53531)]=as.vector(res_covs_snps$risk)}
```

Males

```{r}
rm(list=ls())
library(dplyr)
library(iCARE)
library(eeptools)
library(survminer)
library(survival)

myfem=readRDS("/users/skim1/052020/data/male.final.11182021")

eid=readRDS("/users/skim1/052020/data/male.eid.final.10022021")
index=which(myfem$eid %in% eid)
trfem=myfem[index,]
tefem=myfem[-index,]

colSums(myfem[,c(116:123)])

cox.female=coxph(Surv(age_at_study_entry,cancer_incidence_age,male_overall_cancer_incidence)~blad_std+colo_std+kidn_std+lung_std+mela_std+nhl_std+panc_std+pros_std+factor(bmi)+fhx_yes_no_mal+smoking_status+I(PYOS/10)+pc1+pc2+pc3+pc4+pc5+pc6+pc7+pc8+pc9+pc10,data=trfem)
summary(cox.female)

termL <- attr(terms(cox.female), "term.labels")
a=predict(cox.female,tefem, type="terms",terms=termL[c(1:12)])
head(a)
lpnew.train=rowSums(predict(cox.female,trfem, type="terms",terms=termL[c(1:12)]))
lpnew.test=rowSums(predict(cox.female,tefem, type="terms",terms=termL[c(1:12)]))
lpnew.train.std=lpnew.train/sd(lpnew.train)
lpnew.test.std=lpnew.test/sd(lpnew.test)
trfem$lp=lpnew.train.std
tefem$lp=lpnew.test.std
cox.female.train=coxph(Surv(age_at_study_entry,cancer_incidence_age,male_overall_cancer_incidence)~lp+pc1+pc2+pc3+pc4+pc5+pc6+pc7+pc8+pc9+pc10,data=trfem)
cox.female.test=coxph(Surv(age_at_study_entry,cancer_incidence_age,male_overall_cancer_incidence)~lp+pc1+pc2+pc3+pc4+pc5+pc6+pc7+pc8+pc9+pc10,data=tefem)
concordance(cox.female.test)
summary(cox.female.test)
summary(cox.female.test)$coefficients
library(RISCA)
tefem=data.frame(tefem)
tefem$futime=tefem$cancer_incidence_age-tefem$age_at_study_entry
auc5=roc.time(times="futime", failures="male_overall_cancer_incidence", variable="lp",
                    confounders=~1, data=tefem, 
                    pro.time=5, precision=seq(0.01,0.99, by=0.01))
auc5$auc
##############################################################################
#iCARE 
beta=as.matrix(cox.female.test$coefficients[1])
row.names(beta)="cPRS"
trfem$cPRS=trfem$lp
row.names(beta)="cPRS"
trfem$cPRS=trfem$lp
test=data.frame(tefem$lp)
test=test[order(test),]
test=data.frame(test)
colnames(test)="cPRS"
cal=11
ref=data.frame(rnorm(10000,mean=mean(trfem$lp),sd=sd(trfem$lp)))
colnames(ref)="cPRS"
v1 = list(); v1$name = "cPRS"; v1$type = "continuous"
cov_info_0=list(v1)
model_form_0=male_overall_cancer_incidence ~ cPRS
##############################################################################
incidence_rate=read.csv("/users/skim1/052020/FINAL_SNP_PROJECT/incidence_rate_seer_stat_08122020_male.csv")
inc=incidence_rate[,c(2,14)]
inc[,2]=inc[,2]/100000
##############################################################################
##1YEAR
##############################################################################
age_from=c(50:85)
age_to=age_from+1
age_int=rep(1,length(age_from))
ppv_1yr=matrix(data=NA,nrow=length(age_from), ncol=48240,byrow = FALSE,dimnames = NULL)
##############################################################################
for (i in 1:length(age_from)){
  res_covs_snps=computeAbsoluteRisk(model.formula= model_form_0, 
                                    model.cov.info=cov_info_0, 
                                    model.log.RR=beta,
                                    model.ref.dataset = ref,
                                    model.disease.incidence.rates=inc,
                                    apply.age.start=age_from[i],
                                    apply.age.interval.length = 1,
                                    apply.cov.profile=test)
  ppv_1yr[i,c(1:48240)]=as.vector(res_covs_snps$risk)}
```

