---
title: "Model Building and Absolute Risk Estimation"
output: html_notebook
---

```{r}
set.seed(1)
rm(list=ls())
library(dplyr)
library(iCARE)
library(eeptools)
library(survminer)
library(survival)
myfem=readRDS("/users/skim1/052020/data/final_data_unrelated_white_british_ancestry_plus_prs_remove_prevalent_censor_factors_plus_cancer_incidence_age_3_01242021")
eid=readRDS("/users/skim1/052020/analysis_results/female_primary_analysis/eid_01242021.rds")
trfem=myfem[which(myfem$eid %in% eid),]
tefem=myfem[-which(myfem$eid %in% eid),]
cox.female=coxph(Surv(age_at_study_entry,cancer_incidence_age,female_overall_cancer_incidence)~brea_std+colo_std+endo_std+kidn_std+lung_std+mela_std+nhl_std+ovar_std+bmi+fhx_yes_no_fem+smoking_status+I(PYOS/10)+pc1+pc2+pc3+pc4+pc5+pc6+pc7+pc8+pc9+pc10,data=trfem)
summary(cox.female)
termL <- attr(terms(cox.female), "term.labels")
lpnew.train=rowSums(predict(cox.female,trfem, type="terms",terms=termL[c(1:12)]))
lpnew.test=rowSums(predict(cox.female,tefem, type="terms",terms=termL[c(1:12)]))
lpnew.train.std=lpnew.train/sd(lpnew.train)
lpnew.test.std=lpnew.test/sd(lpnew.test)
trfem$lp=lpnew.train.std
tefem$lp=lpnew.test.std
cox.female.test=coxph(Surv(age_at_study_entry,cancer_incidence_age,female_overall_cancer_incidence)~lp+pc1+pc2+pc3+pc4+pc5+pc6+pc7+pc8+pc9+pc10,data=tefem)
cox.female.train=coxph(Surv(age_at_study_entry,cancer_incidence_age,female_overall_cancer_incidence)~lp+pc1+pc2+pc3+pc4+pc5+pc6+pc7+pc8+pc9+pc10,data=trfem)
```

```{r}
beta=as.matrix(cox.female.test$coefficients[1])
row.names(beta)="cPRS"
trfem$cPRS=trfem$lp
test=data.frame(tefem$lp)
colnames(test)="cPRS"
ref=reference_dataset
colnames(ref)="cPRS"
v1 = list(); v1$name = "cPRS"; v1$type = "continuous"
cov_info_0=list(v1)
model_form_0=female_overall_cancer_incidence ~ cPRS
incidence_rate=read.csv("/users/skim1/052020/FINAL_SNP_PROJECT/incidence_rate_seer_stat_08122020_female.csv")
iii=rowSums(incidence_rate[,c(5:11,13)])
inc=cbind(incidence_rate[,c(2)],iii)
inc[,2]=inc[,2]/100000

age_from=c(50:85)
age_to=age_from+1
age_int=rep(1,length(age_from))
ar_data=matrix(data = NA, nrow = length(age_from), ncol = dim(tefem$lp)[1], byrow = FALSE, dimnames = NULL)

for (i in 1:length(age_from)){
  res_covs_snps=computeAbsoluteRisk(model.formula = model_form_0, 
                                    model.cov.info =cov_info_0, 
                                    model.log.RR = beta,
                                    model.ref.dataset = ref,
                                    model.disease.incidence.rates = inc,
                                    apply.age.start = age_from[i],
                                    apply.age.interval.length = 1,
                                    apply.cov.profile = test)
  ar_data[i,c(1:dim(tefem$lp)[1])]=as.vector(res_covs_snps$risk)*(11/12)}

```


